blueprint:
  name: Keypad - Auth Based On Matched Codes
  description: Authenticate Keypad Based On Matched Codes
  domain: automation
  #source_url: https://github.com/home-assistant/core/blob/master/homeassistant/components/script/blueprints/confirmable_notification.yaml
  author: Lenir Santiago
  input:
    action_script:
      name: Action Script
      selector:
        entity:
          domain:
            - script

mode: single

trigger:
  - platform: event
    event_type: zha_event
    event_data: {}
condition:
  - condition: template
    value_template: >-
      {{ trigger.event.data.args.code|d('undef') is not match('0000',
      ignorecase=False) }}
action:
  - variables:
      user_code_entity: >-
        {{ (expand("group.keypad_user_codes") | reverse |
        selectattr('state','eq',
        trigger.event.data.args.code)|first|d('undef')).entity_id|d('undef')
        }}
      onetime_code_entity: >-
        {{ (expand("group.keypad_onetime_codes") | reverse |
        selectattr('state','eq',
        trigger.event.data.args.code)|first|d('undef')).entity_id|d('undef') }}
      user_name_entity: >-
        {% if user_code_entity == 'undef' %}  undef {% else %} 
        input_text.keypad_name_user_slot_{{user_code_entity[-1]}} {% endif %}
      user_enabled_entity: >-
        {% if user_code_entity == 'undef' %}  undef {% else %} 
        sensor.keypad_enabled_user_slot_{{user_code_entity[-1] }}  {% endif %}
      user_schedule_enabled_entity: >-
        {% if user_code_entity == 'undef' %}  undef {% else %}  
        switch.schedule_keypad_user_slot_{{user_code_entity[-1]}}  {% endif %}
      onetime_user_enabled_entity: >-
        {% if onetime_code_entity == 'undef' %}  undef {% else %}  
        sensor.keypad_enabled_onetime_slot_{{onetime_code_entity[-1]}}  {% endif
        %}
      onetime_user_schedule_enabled_entity: >-
        {% if onetime_code_entity == 'undef' %}  undef {% else %}
        switch.schedule_keypad_user_slot_{{onetime_code_entity[-1]}}  {% endif
        %}
      user_code: "{{states(user_code_entity)}}"
      user_name: "{{states(user_name_entity)}}"
      user_enabled: "{{states(user_enabled_entity)}}"
      user_schedule_enabled: "{{is_state(user_schedule_enabled_entity, 'on')}}"
      user_schedule_active: >-
        {{ is_number(state_attr(user_schedule_enabled_entity, 'current_slot'))
        }}
      is_onetime_user: "{{ has_value(onetime_code_entity) }}"
      onetime_user_enabled: "{{states(onetime_user_enabled_entity)}}"
      onetime_user_schedule_enabled: "{{is_state(onetime_user_schedule_enabled_entity, 'on')}}"
      onetime_user_schedule_active: >-
        {{is_number(state_attr(onetime_user_schedule_enabled_entity,'current_slot'))
        }}
      keypad_rx_code: "{{trigger.event.data.args.code|d('undef')}}"
      keypad_rx_arm_mode: "{{trigger.event.data.args.arm_mode|d('undef')}}"
      keypad_rx_arm_mode_desc: "{{trigger.event.data.args.arm_mode_description|d('undef')}}"
  - service: logbook.log
    data:
      message: >-
        Keypad RX Code[{{keypad_rx_code}}]: {% if is_state(user_code_entity, '')
        == false %} User[{{user_name}}]: Enabled[{{user_enabled}}], Scheduler:
        Enabled[{{user_schedule_enabled}}], Active[{{user_schedule_active }}] 
        {% endif %}  

        One-Time Code [{{is_code_type_onetime}}]:
        Enabled[{{onetime_user_enabled}}], Scheduler:
        Enabled[{{onetime_user_schedule_enabled}}],
        Active[{{onetime_user_schedule_active}}]

        Mode[{{keypad_rx_arm_mode}}]: {{keypad_rx_arm_mode_desc}}
      name: Keypad Log
  - alias: Check all one-time codes
    if:
      - alias: If it matches a one-time code
        condition: template
        value_template: "{{ (has_value(onetime_code_entity)) }}"
    then:
      - service: input_text.set_value
        data:
          entity_id: "{{onetime_entity}}"
          value: "0000"
        alias: Reset to 0000
  - alias: Check all user codes
    if:
      - alias: if it matches any user code including one-time codes
        condition: template
        value_template: "{{ (has_value(user_code_entity) or has_value(onetime_code_entity)) }}"
    then:
      - service: !input action_script
        data:
          message:
            variables:
              user_code_entity: "{{user_code_entity}}"
              onetime_code_entity: "{{onetime_code_entity}}"
              user_name_entity: "{{user_name_entity}}"
              user_enabled_entity: "{{user_enabled_entity}}"
              user_schedule_enabled_entity: "{{user_schedule_enabled_entity}}"
              onetime_user_enabled_entity: "{{onetime_user_enabled_entity}}"
              onetime_user_schedule_enabled_entity: "{{onetime_user_schedule_enabled_entity}}"
              user_code: "{{user_code}}"
              user_name: "{{user_name}}"
              user_enabled: "{{user_enabled}}"
              user_schedule_enabled: "{{user_schedule_enabled}}"
              user_schedule_active: "{{user_schedule_active}}"
              is_onetime_user: "{{is_onetime_user}}"
              onetime_user_enabled: "{{onetime_user_enabled}}"
              onetime_user_schedule_enabled: "{{onetime_user_schedule_enabled}}"
              onetime_user_schedule_active: "{{onetime_user_schedule_active }}"
              keypad_rx_code: "{{keypad_rx_code}}"
              keypad_rx_arm_mode: "{{keypad_rx_arm_mode}}"
              keypad_rx_arm_mode_desc: "{{keypad_rx_arm_mode_desc}}"
